spring:
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 8080

trafficlight:
  data-file: /Users/cjmoon/dev/workspace/traffic-light-search/data/전국신호등표준데이터.json
  index-name: traffic-lights
  bulk-size: 1000
  api:
    base-url: http://api.data.go.kr/openapi/tn_pubr_public_traffic_light_api
    service-key: ${SERVICE_KEY:}
